export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST';
export const LIST_ORDERS_ERROR = 'LIST_ORDERS_ERROR';
export const LIST_ORDERS_RECEIVED = 'LIST_ORDERS_RECEIVED';
export const RESET_LIST_ORDERS_REQUEST = 'RESET_LIST_ORDERS_REQUEST';
export const RESET_LIST_ORDERS_RECEIVED = 'RESET_LIST_ORDERS_RECEIVED';
export const ADD_ORDER = 'ADD_ORDER';
export const MATCH_ORDER = 'MATCH_ORDER';
export const TOGGLE_MATCH = 'TOGGLE_MATCH'